CONTIKI_PROJECT = robotPigeon-main
PROJECT_SOURCEFILES += robotPigeon-shell.c robotPigeon-radio.c
all: $(CONTIKI_PROJECT)

CONTIKI = ../../..
CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include


